# Auto-generated module template — one getter function per register.
# The header is rendered once; then one _FUNC_TEMPLATE block per register.

_HEADER = """\
# Auto-generated by efoy-modbus-config — do not edit manually.
# Source schema : {{ spec.device_name }} {{ spec.version }} (firmware {{ spec.firmware }})
# Register count: {{ regs | length }}
# Register types: {{ reg_types | join(', ') }}
#
# Run `uv run main.py --help` to regenerate with different options.

from __future__ import annotations
import minimalmodbus


"""

_FUNC = """\
def read_{{ reg.name }}(instrument: minimalmodbus.Instrument):
    \"\"\"{{ reg.description | truncate(80, True, '...') }}

    Address : {{ reg.address_dec }} ({{ reg.address_hex }})
    FC      : {{ fc }}
    Type    : {{ reg.data_type.value }}  {{ reg.access }}{% if unit %}  unit={{ unit }}{% endif %}
    \"\"\"
    raw = instrument.read_register({{ reg.address_dec }}, functioncode={{ fc }})
    {% if enum_values -%}
    _labels = {{ enum_values }}
    return _labels.get(str(raw), f"unknown ({raw})")
    {%- else -%}
    return raw{% if scale != 1.0 %} * {{ scale }}{% endif %}
    {%- endif %}

"""
