# Global tags can be specified here in key="value" format.
[global_tags]

[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = ""
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8086"]
  token = "my-super-secret-auth-token"
  organization = "my-org"
  bucket = "efoy"


# Retrieve data from MODBUS slave device: SimDeviceA
[[inputs.modbus]]
  name = "SimDeviceA"
  slave_id = 1
  timeout = "1s"
  controller = "tcp://127.0.0.1:5025"
  configuration_type = "request"

  
  [[inputs.modbus.request]]
    slave_id = 1
    byte_order = "CDAB"
    register = "coil"
    
    fields = [
      
      { address=1, name="SystemOn", type="BIT" }
      
    ]

    [inputs.modbus.request.tags]
      device = "SimDeviceA"
  
  [[inputs.modbus.request]]
    slave_id = 1
    byte_order = "CDAB"
    register = "input"
    
    fields = [
      
      { address=30040, name="SystemState", type="UINT16" }
      
    ]

    [inputs.modbus.request.tags]
      device = "SimDeviceA"
  
  [[inputs.modbus.request]]
    slave_id = 1
    byte_order = "CDAB"
    register = "holding"
    
    fields = [
      
      { address=40003, name="BatBocConfig", type="FLOAT32" }
      
    ]

    [inputs.modbus.request.tags]
      device = "SimDeviceA"
  

# Retrieve data from MODBUS slave device: SimDeviceB
[[inputs.modbus]]
  name = "SimDeviceB"
  slave_id = 2
  timeout = "1s"
  controller = "tcp://127.0.0.1:5025"
  configuration_type = "request"

  
  [[inputs.modbus.request]]
    slave_id = 2
    byte_order = "CDAB"
    register = "coil"
    
    fields = [
      
      { address=2, name="SystemOff", type="BIT" }
      
    ]

    [inputs.modbus.request.tags]
      device = "SimDeviceB"
  
  [[inputs.modbus.request]]
    slave_id = 2
    byte_order = "CDAB"
    register = "input"
    
    fields = [
      
      { address=30023, name="LogUBat", type="FLOAT32" },
      
      { address=30003, name="AssemblyDate", type="UINT32" }
      
    ]

    [inputs.modbus.request.tags]
      device = "SimDeviceB"
  
